In [3]:
import pandas as pd
import numpy as np

/Users/elleobri/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

This is a dataset of the patients who are seen by a particular doctor's office, and the number of COVID-19 vaccinations they have received. We want to understand how many patients are awaiting vaccinations so we can make sure we have enough doses on hand.

In [4]:
df = pd.read_csv('data/patient_vaccination_status.csv')
df.head()

      id  age  n_doses
0  76710   41      0.0
1  83506   24      0.0
2  53477   33      2.0
3  87694   31      1.0
4  62417   19      2.0

Let's create a categorial variable for different age groups, binned into decades. This will be helpful later on if we want to understand if there are any age groups being underserved.

In [10]:
bins = np.arange(0, 101, 10)
labels = [f'{i}-{i+9}' for i in range(0, 100, 10)]
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)
df.head()

      id  age  n_doses age_group
0  76710   41      0.0     40-49
1  83506   24      0.0     20-29
2  53477   33      2.0     30-39
3  87694   31      1.0     30-39
4  62417   19      2.0     10-19

How many patients have never been vaccinated?

In [32]:
# count number of rows where n_doses == 0
n_not_vaccinated = df[df['n_doses'] == 0].shape[0]
print(f'Number of patients never vaccinated: {n_not_vaccinated}')

Number of patients never vaccinated: 303

The COVID-19 vaccination typically requires multiple doses, depending on the specific vaccine given. For this dataset, let's assume that 2 doses is considered fully vaccinated. How many patients are fully vaccinated? How many are partially vaccinated?

In [37]:
any_vaccine = df[df['n_doses'] != 0]
n_any_vaccine = any_vaccine.shape[0]
# Print out how many patients have received any vaccine
print(f'Number of patients who have received at least one dose: {n_any_vaccine}')

any_vaccine.n_doses.value_counts()

Number of patients who have received at least one dose: 697

1.0    310
2.0    299
Name: n_doses, dtype: int64

Wait a second- these numbers don't quite add up. Shouldn't the counts of patients with 1 and 2 doses each add up to the total number of patients with any vaccine? What's going on here?