In [106]:
import pandas as pd

## Retrieve data

In [107]:
data = pd.read_csv("./mega_millions_pick5_cols-2002_24.csv")

In [108]:
data.head(3)

,draw_date,winning_numbers,mega_ball,multiplier,pick5_1,pick5_2,pick5_3,pick5_4,pick5_5
0,05/17/2024,08 17 40 60 70,3,2.0,8,17,40,60,70
1,05/14/2024,13 19 43 62 64,6,3.0,13,19,43,62,64
2,05/10/2024,13 22 26 32 65,18,4.0,13,22,26,32,65

## Convert Draw Date

In [109]:
data.loc[:, "draw_date"] = pd.to_datetime(data.loc[:, "draw_date"])

## Melt Data

Unpivot from wide to long format

In [110]:
columns = data.columns.tolist()
data_m = data.melt(
    id_vars=["draw_date"], value_vars=columns[1:], var_name="variable", value_name="value"
).sort_values(by=["draw_date", "variable"], ascending=[False, True], ignore_index=True)

data_m.head(24)

    draw_date         variable           value
0  2024-05-17        mega_ball               3
1  2024-05-17       multiplier             2.0
2  2024-05-17          pick5_1               8
3  2024-05-17          pick5_2              17
4  2024-05-17          pick5_3              40
5  2024-05-17          pick5_4              60
6  2024-05-17          pick5_5              70
7  2024-05-17  winning_numbers  08 17 40 60 70
8  2024-05-14        mega_ball               6
9  2024-05-14       multiplier             3.0
10 2024-05-14          pick5_1              13
11 2024-05-14          pick5_2              19
12 2024-05-14          pick5_3              43
13 2024-05-14          pick5_4              62
14 2024-05-14          pick5_5              64
15 2024-05-14  winning_numbers  13 19 43 62 64
16 2024-05-10        mega_ball              18
17 2024-05-10       multiplier             4.0
18 2024-05-10          pick5_1              13
19 2024-05-10          pick5_2              22
20 2024-05-10          pick5_3              26
21 2024-05-10          pick5_4              32
22 2024-05-10          pick5_5              65
23 2024-05-10  winning_numbers  13 22 26 32 65

In [111]:
data_m.shape

(18352, 3)

## Convert datetime back to original string format

Gotcha: [`astype()` and `loc()` behaviors](https://pandas.pydata.org/docs/user_guide/basics.html#astype)

> When trying to convert a subset of columns to a specified type using astype() and loc(), upcasting occurs.
>
> loc() tries to fit in what we are assigning to the current dtypes, while [] will overwrite them taking the dtype from the right hand side. Therefore the following piece of code produces the unintended result.

In [112]:
data_m["draw_date"] = data_m["draw_date"].dt.strftime("%m/%d/%Y")  # works
# data_m.loc[:, "draw_date"] = data_m.loc["draw_date"].dt.strftime("%m/%d/%Y")  # fails due to loc() upcasting
data_m.dtypes

draw_date    object
variable     object
value        object
dtype: object

In [113]:
data_m.head(3)

    draw_date    variable value
0  05/17/2024   mega_ball     3
1  05/17/2024  multiplier   2.0
2  05/17/2024     pick5_1     8

In [114]:
data_m.to_csv("./mega_millions_long_format-2002_24.csv", index=False)